services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bitlab_portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python manage.py migrate --noinput && gunicorn bitlab_portfolio.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-change-me}
      - POSTGRES_DB=bitlab_portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,web,72.60.252.126,8bitlab.com.br,www.8bitlab.com.br
      - CSRF_TRUSTED_ORIGINS=http://72.60.252.126,https://8bitlab.com.br,https://www.8bitlab.com.br,http://8bitlab.com.br,http://www.8bitlab.com.br
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
